services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  superlinked:
    build:
      context: ./superlinked_app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GPU_EMBEDDING_THRESHOLD=1
      - PYTHONPATH=/app
      - APP_MODULE_PATH=superlinked_app
      - WORKER_COUNT=1
    volumes:
      - ./data:/app/data:ro
      - ./superlinked_app:/app/superlinked_app:ro
      - ./superlinked_app/.env:/app/.env:ro
    depends_on:
      - qdrant
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - SUPERLINKED_URL=http://superlinked:8080
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./.env:/app/.env:ro
      - ./scripts:/app/scripts:ro
    depends_on:
      - superlinked

volumes:
  qdrant_data: